# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gengyuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u5f00\u57a6\u8352\u5730', max_length=255, verbose_name='\u8015\u8018')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(help_text='\u7528\u6237\u7ed1\u5b9a', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='zhongzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u64ad\u79cd')),
                ('text', models.TextField(verbose_name='\u79cd\u5b50\u63cf\u8ff0')),
                ('gengyuns_id', models.ForeignKey(help_text='\u7ed1\u5b9a\u8352\u5730', on_delete=django.db.models.deletion.CASCADE, to='gengyun.gengyuns', verbose_name='\u8015\u8018')),
            ],
        ),
    ]
