# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gengyun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gengyuns',
            name='text',
            field=models.TextField(blank=True, verbose_name='\u8352\u5730\u63cf\u8ff0'),
        ),
    ]
