# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gengyun', '0002_gengyuns_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhongzi',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 5, 14, 21, 7, 790000)),
            preserve_default=False,
        ),
    ]
